// src/app/metadata.ts
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Wahlen Dialer",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};
